server:
  port: 8000


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3317/neusoftoa?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
      
mybatis:
  mapper-locations:
  - classpath*:/mappers/**/*.xml
  type-aliases-package: com.neusoft.oa.hrservice.model
 
logging:
  level:
    com.neusoft.oa.hr.mapper: debug
    



